// Code generated by mockery v1.0.0. DO NOT EDIT.

package marcopoller_test

import mock "github.com/stretchr/testify/mock"

import slack "github.com/nlopes/slack"

// UserFinder is an autogenerated mock type for the UserFinder type
type UserFinder struct {
	mock.Mock
}

// GetUserInfo provides a mock function with given fields: user
func (_m *UserFinder) GetUserInfo(user string) (*slack.User, error) {
	ret := _m.Called(user)

	var r0 *slack.User
	if rf, ok := ret.Get(0).(func(string) *slack.User); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*slack.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
