// Code generated by mockery v1.0.0. DO NOT EDIT.

package marcopoller_test

import http "net/http"

import mock "github.com/stretchr/testify/mock"

// Verifier is an autogenerated mock type for the Verifier type
type Verifier struct {
	mock.Mock
}

// Verify provides a mock function with given fields: header, body
func (_m *Verifier) Verify(header http.Header, body []byte) error {
	ret := _m.Called(header, body)

	var r0 error
	if rf, ok := ret.Get(0).(func(http.Header, []byte) error); ok {
		r0 = rf(header, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
